"""
Post-hoc curation of on-policy SFT data generated by create_musique_sft_onpolicy.py.

Two curation modes:

  Heuristic (default, no LLM calls):
    Filter 1 — Minimal queries:
      total search queries ≤ N_uncertain_hops + --max-extra-queries (default 2)
    Filter 2 — Answer found in results:
      for every uncertain hop, its gold answer appears (case-insensitive
      substring) in at least one search result text in the trace.

  LLM-as-judge (--use-llm):
    Per-query LLM attribution to a hop (0-based; -1 = aggregate/general),
    mirroring scripts/analyze_parametric_search_interplay.py.
    Filter 1 — Minimal queries:
      Same total-query bound as heuristic mode, plus per-uncertain-hop:
      ≥1 query attributed to the hop (LLM-verified R2).
    Filter 2 — Answer found in results:
      For each uncertain hop, at least one query attributed to it has the
      gold answer present in its search results. Substring by default;
      use --llm-gold-check for the LLM semantic judge.

Caches are stored under <output dir>/curation_cache/ and reused across runs
unless --reattribute is passed.

Usage:
    # Heuristic (default)
    uv run python scripts/curate_onpolicy_sft.py \\
        --input-jsonl data/sft/musique_onpolicy/procedure1_onpolicy_sft.jsonl \\
        --uncertainty-json results/musique_parametric/musique_parametric_uncertainty_nemotron-3-nano_30b.json \\
        --natural-jsonl data/musique_train_natural.jsonl \\
        --dry-run

    # LLM judge (per-query attribution)
    uv run python scripts/curate_onpolicy_sft.py \\
        --input-jsonl data/sft/musique_onpolicy/procedure1_onpolicy_sft.jsonl \\
        --uncertainty-json results/musique_parametric/musique_parametric_uncertainty_nemotron-3-nano_30b.json \\
        --natural-jsonl data/musique_train_natural.jsonl \\
        --use-llm --attribution-model gpt-oss:20b --attribution-provider ollama \\
        --llm-gold-check
"""

import argparse
import ast
import hashlib
import json
import os
import re
import sys
from pathlib import Path
from typing import Literal

from pydantic import BaseModel

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))


# ─── Pydantic models (mirrors analyze_parametric_search_interplay.py) ─────────

class QueryAttribution(BaseModel):
    hop_index: int  # 0-based; -1 = aggregate/general
    confidence: Literal["high", "medium", "low"]
    reasoning: str


class GoldFoundJudgment(BaseModel):
    found: bool
    reasoning: str


# ─── Prompts (verbatim from analyze_parametric_search_interplay.py) ───────────

ATTRIBUTION_PROMPT = """You are attributing a search query issued by an AI agent to one of the sub-questions (hops) that make up a multi-hop question.

Aggregate question: {aggregate_question}

Sub-questions (hops):
{sub_questions_text}

Agent's thinking before the search query:
{thinking}

Search query: {query}

Which sub-question (hop) is this search query primarily trying to answer?
Return the 0-based hop_index (0, 1, 2, ...) or -1 if the query is about the aggregate question or doesn't clearly target a specific sub-question.
"""

GOLD_FOUND_PROMPT = """You are checking whether a specific answer is semantically present in search results.

Gold answer: {gold_answer}

Search results:
{search_text}

Is the gold answer (or an equivalent phrasing/abbreviation) present in the search results above?
Answer True if the search results contain the answer or a clear equivalent.
Answer False if the answer is absent or only tangentially mentioned without being stated as a fact.
"""


# ─── Helpers ──────────────────────────────────────────────────────────────────

THINK_BLOCK = re.compile(r"<think>(.*?)</think>", re.DOTALL)


def normalize(s: str) -> str:
    return re.sub(r'\s+', ' ', s.lower().strip())


def extract_thinking(content: str) -> str:
    """Pull <think>...</think> body from assistant content."""
    if not content:
        return ""
    matches = THINK_BLOCK.findall(content)
    return "\n".join(m.strip() for m in matches)


def parse_search_results(content: str) -> tuple[str, list[str]]:
    """Parse tool message content (stringified list-of-dicts) into (concat_text, snippets)."""
    if not content:
        return "", []
    try:
        data = ast.literal_eval(content)
    except (ValueError, SyntaxError):
        try:
            data = json.loads(content)
        except json.JSONDecodeError:
            return content, [content]
    if not isinstance(data, list):
        return str(data), [str(data)]
    snippets = [
        f"{r.get('title', '')} {r.get('snippet', '')}".strip()
        for r in data
        if isinstance(r, dict)
    ]
    return " ".join(snippets), snippets


def extract_queries_and_results(messages: list[dict]) -> list[dict]:
    """Extract per-query records: {query, thinking, query_index, result_text, snippets, tool_call_id}.

    Multiple tool_calls in one assistant message share that turn's thinking. Each
    query's results come from the matching tool message via tool_call_id.
    """
    records: list[dict] = []
    query_index = 0

    for turn_idx, msg in enumerate(messages):
        if msg["role"] != "assistant" or not msg.get("tool_calls"):
            continue
        thinking = extract_thinking(msg.get("content", ""))

        # Build tool_call_id → (text, snippets) from the next tool message(s)
        result_map: dict[str, tuple[str, list[str]]] = {}
        for following in messages[turn_idx + 1:]:
            if following["role"] != "tool":
                break
            tcid = following.get("tool_call_id", "")
            result_map[tcid] = parse_search_results(following.get("content", ""))

        for tc in msg["tool_calls"]:
            try:
                args = json.loads(tc["function"]["arguments"])
                query = args["query"]
            except (KeyError, json.JSONDecodeError):
                continue
            tcid = tc.get("id", "")
            text, snippets = result_map.get(tcid, ("", []))
            records.append({
                "query": query,
                "thinking": thinking,
                "query_index": query_index,
                "result_text": text,
                "snippets": snippets,
                "tool_call_id": tcid,
            })
            query_index += 1
    return records


def load_natural_map(path: str) -> dict[str, dict]:
    m: dict[str, dict] = {}
    with open(path) as f:
        for line in f:
            rec = json.loads(line)
            m[rec["text"]] = rec
    return m


def load_uncertainty_by_id(path: str) -> dict[str, dict]:
    with open(path) as f:
        data = json.load(f)
    return {ex["example_id"]: ex for ex in data}


def get_uncertain_hops(sub_questions: list[dict]) -> list[tuple[int, str]]:
    return [
        (sq["hop_index"], sq["gold_answer"])
        for sq in sub_questions
        if sq.get("semantic_entropy", 0) > 0
    ]


# ─── Heuristic mode helpers ───────────────────────────────────────────────────

def answer_in_results_heuristic(gold_answer: str, result_texts: list[str]) -> bool:
    normed = normalize(gold_answer)
    if len(normed) < 3:
        return True
    combined = normalize(" ".join(result_texts))
    return normed in combined


# ─── LLM mode helpers ─────────────────────────────────────────────────────────

def llm_attribute(
    query_rec: dict,
    sub_questions: list[dict],
    aggregate_question: str,
    agent,
    cache: dict,
    cache_key: str,
    reattribute: bool,
) -> QueryAttribution:
    if not reattribute and cache_key in cache:
        return QueryAttribution(**cache[cache_key])

    sub_q_text = "\n".join(
        f"  Hop {sq['hop_index']}: {sq['question']}" for sq in sub_questions
    )
    prompt = ATTRIBUTION_PROMPT.format(
        aggregate_question=aggregate_question,
        sub_questions_text=sub_q_text,
        thinking=query_rec["thinking"][:500],
        query=query_rec["query"],
    )
    try:
        result = agent.run(prompt)
        attribution = result.output
    except Exception as e:
        print(f"    LLM attribution error: {e} — defaulting to -1")
        attribution = QueryAttribution(
            hop_index=-1, confidence="low", reasoning=f"Error: {e}"
        )

    cache[cache_key] = attribution.model_dump()
    return attribution


def llm_gold_found(
    gold_answer: str,
    snippets: list[str],
    agent,
    cache: dict,
    cache_key: str,
    reattribute: bool,
) -> bool:
    if not reattribute and cache_key in cache:
        return cache[cache_key]["found"]

    numbered = "\n".join(f"{i + 1}. {s}" for i, s in enumerate(snippets) if s)
    prompt = GOLD_FOUND_PROMPT.format(gold_answer=gold_answer, search_text=numbered)
    try:
        result = agent.run(prompt)
        found = bool(result.output.found)
    except Exception as e:
        print(f"    LLM gold-found error: {e} — falling back to substring")
        joined = " ".join(snippets)
        found = bool(gold_answer) and gold_answer.lower() in joined.lower()

    cache[cache_key] = {"found": found}
    return found


def load_cache(path: str, reattribute: bool) -> dict:
    if reattribute or not os.path.exists(path):
        return {}
    with open(path) as f:
        return json.load(f)


def save_cache(path: str, cache: dict) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(cache, f)


# ─── CLI ──────────────────────────────────────────────────────────────────────

def setup_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Curate on-policy SFT data via heuristics or LLM-as-judge."
    )
    p.add_argument("--input-jsonl", required=True)
    p.add_argument("--uncertainty-json", required=True)
    p.add_argument("--natural-jsonl", required=True)
    p.add_argument("--output-jsonl", default=None,
                   help="Output path (default: <input>_curated.jsonl)")
    p.add_argument("--max-extra-queries", type=int, default=2,
                   help="Max extra queries above N_uncertain_hops (default: 2)")
    p.add_argument("--dry-run", action="store_true")
    # LLM mode
    p.add_argument("--use-llm", action="store_true",
                   help="Use LLM judge for query→hop attribution (mirrors "
                        "analyze_parametric_search_interplay.py).")
    p.add_argument("--attribution-model", default="gpt-oss:20b",
                   help="LLM attribution model name (default: gpt-oss:20b)")
    p.add_argument("--attribution-provider", default="ollama",
                   help="LLM attribution provider (default: ollama)")
    p.add_argument("--attribution-ollama-url", default=None,
                   help="Ollama base URL for attribution agent.")
    p.add_argument("--llm-gold-check", action="store_true",
                   help="Use LLM to semantically judge whether gold answer is "
                        "present in search results (default: substring). "
                        "Requires --use-llm.")
    p.add_argument("--reattribute", action="store_true",
                   help="Ignore on-disk attribution cache and redo all LLM calls.")
    return p.parse_args()


# ─── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    args = setup_args()

    if args.output_jsonl is None:
        stem = Path(args.input_jsonl).stem
        parent = Path(args.input_jsonl).parent
        suffix = "_curated_llm" if args.use_llm else "_curated"
        args.output_jsonl = str(parent / f"{stem}{suffix}.jsonl")

    if args.llm_gold_check and not args.use_llm:
        print("WARN: --llm-gold-check requires --use-llm. Falling back to substring.")
        args.llm_gold_check = False

    print("Loading natural paraphrases...")
    natural_map = load_natural_map(args.natural_jsonl)
    print(f"  {len(natural_map)} entries")

    print("Loading uncertainty data...")
    uncertainty_by_id = load_uncertainty_by_id(args.uncertainty_json)
    print(f"  {len(uncertainty_by_id)} examples")

    records: list[dict] = []
    with open(args.input_jsonl) as f:
        for line in f:
            records.append(json.loads(line))
    print(f"Input records: {len(records)}\n")

    # LLM-mode setup
    attribution_agent = None
    gold_judge_agent = None
    attr_cache: dict = {}
    gold_cache: dict = {}
    cache_dir = os.path.join(Path(args.output_jsonl).parent, "curation_cache")
    attr_cache_path = os.path.join(cache_dir, "attribution_cache.json")
    gold_cache_path = os.path.join(cache_dir, "gold_check_cache.json")

    if args.use_llm:
        from src.services.base_agent import BaseAgent
        print(f"Initializing attribution agent "
              f"({args.attribution_provider}/{args.attribution_model})...")
        attribution_agent = BaseAgent(
            model_name=args.attribution_model,
            provider_name=args.attribution_provider,
            output_type=QueryAttribution,
            agent_name="CurationAttributionAgent",
            use_thinking=False,
            ollama_base_url=args.attribution_ollama_url,
        )
        attr_cache = load_cache(attr_cache_path, args.reattribute)
        print(f"  {len(attr_cache)} cached attributions")

        if args.llm_gold_check:
            gold_judge_agent = BaseAgent(
                model_name=args.attribution_model,
                provider_name=args.attribution_provider,
                output_type=GoldFoundJudgment,
                agent_name="CurationGoldFoundJudge",
                use_thinking=False,
                ollama_base_url=args.attribution_ollama_url,
            )
            gold_cache = load_cache(gold_cache_path, args.reattribute)
            print(f"  {len(gold_cache)} cached gold-found judgments")

    kept: list[dict] = []
    fail_query = 0
    fail_answer = 0
    fail_both = 0
    unmatched = 0

    for rec_idx, rec in enumerate(records):
        messages = rec["messages"]
        user_q = messages[1]["content"]

        nat_rec = natural_map.get(user_q)
        if nat_rec is None:
            print(f"  WARN: no natural match for: {user_q[:80]!r}")
            unmatched += 1
            continue

        eid = nat_rec["example_id"]
        unc_ex = uncertainty_by_id.get(eid)
        if unc_ex is None:
            print(f"  WARN: no uncertainty data for {eid}")
            unmatched += 1
            continue

        sub_questions = unc_ex["sub_questions_results"]
        aggregate_q = unc_ex["aggregate_question"]
        uncertain_hops = get_uncertain_hops(sub_questions)
        queries = extract_queries_and_results(messages)

        # ─── Filter 1 — total query count bound (both modes) ──────────────────
        passes_query = len(queries) <= len(uncertain_hops) + args.max_extra_queries

        # ─── Filter 2 — answer in results ─────────────────────────────────────
        if not args.use_llm:
            # Heuristic: any uncertain hop's gold answer in any result
            all_result_texts = [q["result_text"] for q in queries]
            passes_answer = all(
                answer_in_results_heuristic(gold_ans, all_result_texts)
                for _, gold_ans in uncertain_hops
            )
        else:
            # LLM: per-query attribution → per-hop gold check
            print(f"  [{rec_idx + 1}/{len(records)}] {eid}: "
                  f"{len(queries)} queries, {len(uncertain_hops)} uncertain hops")
            attributions: list[QueryAttribution] = []
            for q in queries:
                ck = f"{eid}:q{q['query_index']}"
                attributions.append(llm_attribute(
                    q, sub_questions, aggregate_q,
                    attribution_agent, attr_cache, ck, args.reattribute,
                ))

            # Tighten filter 1: every uncertain hop must have ≥1 query attributed
            hop_to_queries: dict[int, list[dict]] = {}
            for q, a in zip(queries, attributions):
                hop_to_queries.setdefault(a.hop_index, []).append(q)
            r2_satisfied = all(
                hop_idx in hop_to_queries for hop_idx, _ in uncertain_hops
            )
            passes_query = passes_query and r2_satisfied

            # Per-hop gold check
            passes_answer = True
            for hop_idx, gold_ans in uncertain_hops:
                hop_queries = hop_to_queries.get(hop_idx, [])
                if not hop_queries:
                    passes_answer = False
                    break
                if args.llm_gold_check:
                    found_for_hop = False
                    for q in hop_queries:
                        snip_digest = hashlib.md5(
                            "|".join(s[:100] for s in q["snippets"]).encode()
                        ).hexdigest()[:16]
                        ans_digest = hashlib.md5(gold_ans.encode()).hexdigest()[:16]
                        gck = f"gf:{ans_digest}:{snip_digest}"
                        if llm_gold_found(
                            gold_ans, q["snippets"],
                            gold_judge_agent, gold_cache, gck, args.reattribute,
                        ):
                            found_for_hop = True
                            break
                    if not found_for_hop:
                        passes_answer = False
                        break
                else:
                    result_texts = [q["result_text"] for q in hop_queries]
                    if not answer_in_results_heuristic(gold_ans, result_texts):
                        passes_answer = False
                        break

            # Persist caches periodically
            if (rec_idx + 1) % 20 == 0:
                save_cache(attr_cache_path, attr_cache)
                if args.llm_gold_check:
                    save_cache(gold_cache_path, gold_cache)

        if passes_query and passes_answer:
            kept.append(rec)
        elif not passes_query and not passes_answer:
            fail_both += 1
        elif not passes_query:
            fail_query += 1
        else:
            fail_answer += 1

    # Final cache flush
    if args.use_llm:
        save_cache(attr_cache_path, attr_cache)
        if args.llm_gold_check:
            save_cache(gold_cache_path, gold_cache)

    total = len(records)
    kept_n = len(kept)
    rejected_n = total - kept_n - unmatched
    mode_label = "LLM-as-judge" if args.use_llm else "heuristic"

    print("=" * 50)
    print(f"Mode:                      {mode_label}")
    print(f"Total records:             {total:5d}")
    print(f"Unmatched (warn):          {unmatched:5d}")
    print(f"Passed both filters:       {kept_n:5d}")
    print(f"Rejected total:            {rejected_n:5d}")
    print(f"  query count only:        {fail_query:5d}")
    print(f"  answer not found only:   {fail_answer:5d}")
    print(f"  both filters failed:     {fail_both:5d}")
    print("=" * 50)

    if args.dry_run:
        print("\n[dry-run] No output written.")
        return

    with open(args.output_jsonl, "w") as f:
        for rec in kept:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    print(f"\nWrote {kept_n} records → {args.output_jsonl}")


if __name__ == "__main__":
    main()
