"""
ShareChat Parametric Uncertainty Experiment

For each ShareChat question (with substrate questions generated by
label_sharechat_substrates.py), probes each substrate question N times
(no search) and computes semantic entropy to measure parametric uncertainty.

Output JSON is compatible with analyze_parametric_search_interplay.py
(with --no-gold-answer flag) and mirrors the structure of
musique_parametric_uncertainty_*.json.

Usage:
  uv run python scripts/run_sharechat_parametric_uncertainty.py \\
      --substrates data/sharechat_substrates.jsonl \\
      --model gemma4:31b --provider ollama \\
      --num-runs 5 \\
      --output-dir results/sharechat_parametric/ \\
      --resume
"""

import argparse
import json
import os
import sys
import time

import httpx

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.services.base_agent import BaseAgent
from scripts.run_musique_parametric_uncertainty import (
    HopAnswer,
    build_clusterer,
    compute_semantic_entropy,
)


def setup_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="ShareChat parametric uncertainty experiment (substrate probing)."
    )
    parser.add_argument("--substrates", required=True,
                        help="Path to substrate JSONL from label_sharechat_substrates.py.")
    parser.add_argument("--model", default="gemma4:31b",
                        help="Model to probe for parametric uncertainty (default: gemma4:31b).")
    parser.add_argument("--provider", default="ollama",
                        help="Provider for the probing model (default: ollama).")
    parser.add_argument("--num-runs", type=int, default=5,
                        help="Parametric probing runs per substrate question (default: 5).")
    parser.add_argument("--output-dir", default="results/sharechat_parametric",
                        help="Output directory (default: results/sharechat_parametric).")
    parser.add_argument("--resume", action="store_true",
                        help="Skip already-completed example IDs.")
    parser.add_argument("--ollama-url", default=None,
                        help="Ollama base URL for the probing model.")
    parser.add_argument("--clusterer-ollama-url", default=None,
                        help="Ollama base URL for the clustering judge (gpt-oss:120b).")
    return parser.parse_args()


def load_substrates(path: str) -> list[dict]:
    items = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                items.append(json.loads(line))
    return items


def probe_substrate_question(
    agent: BaseAgent,
    question: str,
    max_retries: int = 5,
) -> dict:
    """Run one no-search probe on a substrate question. Returns {reasoning, final_answer}."""
    for attempt in range(max_retries):
        try:
            response = agent.run(question)
            hop_answer: HopAnswer = response.output
            return {
                "reasoning": hop_answer.reasoning,
                "final_answer": hop_answer.final_answer,
            }
        except (httpx.ConnectError, httpx.RemoteProtocolError, ConnectionError) as e:
            if attempt < max_retries - 1:
                wait = 2 ** attempt
                print(f"    Network error (attempt {attempt+1}/{max_retries}): {e}. Retrying in {wait}s...")
                time.sleep(wait)
            else:
                print(f"    Failed after {max_retries} attempts.")
                return {"reasoning": "", "final_answer": f"ERROR: {e}"}
        except Exception as e:
            if attempt < max_retries - 1:
                wait = 2 ** attempt
                print(f"    Error (attempt {attempt+1}/{max_retries}): {e}. Retrying in {wait}s...")
                time.sleep(wait)
            else:
                print(f"    Failed after {max_retries} attempts: {e}")
                return {"reasoning": "", "final_answer": f"ERROR: {e}"}


def main() -> None:
    args = setup_args()

    model_slug = args.model.replace("/", "_").replace(":", "_")
    output_filename = f"sharechat_parametric_uncertainty_{model_slug}.json"
    os.makedirs(args.output_dir, exist_ok=True)
    output_path = os.path.join(args.output_dir, output_filename)

    # Resume support
    existing_results: list[dict] = []
    completed_ids: set[str] = set()
    if args.resume and os.path.exists(output_path):
        with open(output_path) as f:
            existing_results = json.load(f)
        completed_ids = {r["example_id"] for r in existing_results}
        print(f"Resuming: {len(completed_ids)} examples already completed.")

    substrates = load_substrates(args.substrates)
    print(f"Loaded {len(substrates)} substrate entries from {args.substrates}")

    print(f"Initializing probing agent ({args.model} via {args.provider})...")
    probe_agent = BaseAgent(
        provider_name=args.provider,
        model_name=args.model,
        output_type=HopAnswer,
        agent_name=f"sharechat_parametric_{model_slug}",
        ollama_base_url=args.ollama_url,
    )

    clusterer = build_clusterer(ollama_base_url=args.clusterer_ollama_url)

    print(f"\n--- ShareChat Parametric Uncertainty: {args.model}, {args.num_runs} runs/substrate ---")
    print(f"Examples: {len(substrates)}, Output: {output_path}\n")

    results = list(existing_results)

    for i, item in enumerate(substrates):
        example_id = item["example_id"]
        if example_id in completed_ids:
            print(f"[{i+1}/{len(substrates)}] Skipping {example_id} (already done)")
            continue

        question = item["question"]
        print(f"[{i+1}/{len(substrates)}] {example_id}: {question[:70]}...")

        sub_questions_results = []
        for sq in item.get("substrate_questions", []):
            hop_idx = sq["hop_index"]
            probe_q = sq["question"]
            print(f"  Substrate {hop_idx}: {probe_q[:80]}")

            runs = []
            for run_i in range(args.num_runs):
                print(f"    Run {run_i+1}/{args.num_runs}...")
                run_result = probe_substrate_question(probe_agent, probe_q)
                runs.append(run_result)

            semantic_entropy, cluster_ids = compute_semantic_entropy(
                clusterer, probe_q, runs
            )

            sub_questions_results.append({
                "hop_index": hop_idx,
                "question": probe_q,
                "gold_answer": "",           # no gold answers for ShareChat
                "runs": runs,
                "num_correct": 0,            # not applicable without gold answer
                "num_runs": args.num_runs,
                "semantic_entropy": semantic_entropy,
                "cluster_ids": cluster_ids,
            })

        entry = {
            "example_id": example_id,
            "aggregate_question": question,
            "aggregate_result": None,        # traces already exist; not re-run here
            "sub_questions_results": sub_questions_results,
        }
        results.append(entry)

        with open(output_path, "w") as f:
            json.dump(results, f, indent=2)

        avg_entropy = (
            sum(r["semantic_entropy"] for r in sub_questions_results) / len(sub_questions_results)
            if sub_questions_results else 0.0
        )
        n_certain = sum(1 for r in sub_questions_results if r["semantic_entropy"] <= 0.0)
        print(f"  -> avg_entropy={avg_entropy:.3f} bits, "
              f"certain={n_certain}/{len(sub_questions_results)} substrates")

    print(f"\n--- Done. {len(results)} results saved to {output_path} ---")


if __name__ == "__main__":
    main()
